### ISSUE TITLE
Rename broken?

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/ModPackDownloader#24]
http://play.nincraft.com:8080/job/Undead_Zeratul%20Org/job/ThereWillBeBlood/branch/release%252Fv1.0.0/1/console

**Comment by Nincodedo** [comment]
Had to clear the cache. Seems to have fixed the issue.

**Comment by UndeadZeratul** [comment]
http://play.nincraft.com:8080/job/Undead_Zeratul%20Org/job/ThereWillBeBlood/branch/master/2/console

Seems it's still broken, and according to [this line](https://github.com/Nincraft/ModPackDownloader/blob/develop/src/main/java/com/nincraft/modpackdownloader/handler/ForgeHandler.java#L81), it's trying to take the renamed filename, when in reality, it doesn't get renamed in the local cache.

**Comment by Nincodedo** [comment]
Really this whole thing needs to be refactored, but yes. It's not looking for the right thing to copy.
