### ISSUE TITLE
Github release downloader

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/ModPackDownloader#25]
This handler will have mod name, repo name, and release tag. This will only work with github repos that utilize the releases tab and actually tag their builds.

**Comment by Nincodedo** [comment]
Closing in favor of https://github.com/Nincraft/ModPackDownloader/projects/1

**Comment by UndeadZeratul** [comment]
Turns out you can just add existing issues to projects, so we can keep this open.

**Comment by Nincodedo** [comment]
Gonna close this for now as this doesn't seem all that useful. Very few mods only release on Github.
