### ISSUE TITLE
Github release updater

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/ModPackDownloader#26]
Only will work with repos that use the releases tab. Main issue will be lack of knowing which Minecraft version the releases are set for. Still need to work that out.

**Comment by Nincodedo** [comment]
https://github.com/Nincraft/ModPackDownloader/projects/1

**Comment by UndeadZeratul** [comment]
Turns out you can just add existing issues to projects, so we can keep this open.

**Comment by Nincodedo** [comment]
Gonna close this for now as this doesn't seem all that useful. Very few mods only release on Github.
