### ISSUE TITLE
Modpack updating

### ISSUE THREAD

**Issue by Watchful1** [Nincraft/ModPackDownloader#28]
A json of modpack details can be accessed through the widget api like so.

https://widget.mcf.li/modpacks/minecraft/225550-agrarian-skies-2.json

This feature would store the slug, 225550-agrarian-skies-2, in a file in the minecraft folder. The application could then be run with a command line argument of the minecraft folder, or simply stored in that folder and run without location specific arguments, and update the pack to the current recommended version.

In theory this could be combined with MultiMC's ability to run programs before instance launch to update packs on the fly.

**Comment by Nincodedo** [comment]
https://github.com/Nincraft/ModPackDownloader/tree/feature/curse-modpack-downloader Your thoughts so far? Running the jar with the argument -updateCurseModPack and a file called modpackid with the project slug is all you need.

**Comment by Watchful1** [comment]
Getting

```
$ java -jar ModPackDownloader.jar -updateCurseModPack
20:35:04.112 [main] INFO  com.nincraft.modpackdownloader.ModPackDownloader:46 - No mod folder specified, defaulting to "mods"
20:35:04.152 [main] INFO  com.nincraft.modpackdownloader.manager.ModPackManager:23 - Found modpackid file with id ftb-unstable-1-9

Exception in thread "main" java.lang.NumberFormatException: For input string: "ftb"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.nincraft.modpackdownloader.container.CurseFile.<init>(CurseFile.java:45)
        at com.nincraft.modpackdownloader.manager.ModPackManager.updateModPack(ModPackManager.java:30)
        at com.nincraft.modpackdownloader.ModPackDownloader.main(ModPackDownloader.java:32)
```

Slugs don't necessarily start with, or even contain, the project ID. It changed a few months ago, so new projects usually don't have them.

**Comment by Nincodedo** [comment]
Oops. I'll have to grab the project ID from the JSON I guess. I need that for downloading.

**Comment by Nincodedo** [comment]
That pack's slug still has the project ID in it. http://mods.curse.com/modpacks/minecraft/238015-ftb-unstable-1-9

Widget too https://widget.mcf.li/modpacks/minecraft/238015-ftb-unstable-1-9.json

**Comment by Watchful1** [comment]
Hmm, interesting. It makes sense that both would resolve. So I guess it's just a question of usability. If you're just starting from [here](http://www.feed-the-beast.com/modpacks), I don't see a way to get the slug with the project ID.

Your choice, but I would recommend relying on the known api over the end user input string.

**Comment by Nincodedo** [comment]
If you go to a pack and click View on Curse, it goes to a URL with the project ID usually.

**Comment by Nincodedo** [comment]
I added a few more fixes and was able to download a FTB pack but only if you supply the ID and name. But yeah, I'm not sure how else to get the project ID with just the name.

**Comment by Watchful1** [comment]
Ah, fair enough.

**Comment by Watchful1** [comment]
Yup, that worked perfectly. I don't think it's going to update forge in MultiMC, but you would probably have to add special compatibility for that.

**Comment by Nincodedo** [comment]
I was looking into updating Forge, however it seems rather complicated. I already have downloading the installer and universal done, but there's a net.minecraftforge.json in the instance that needs to be updated so it runs with the right Forge and libraries. Not sure how to go about that yet.

**Comment by Nincodedo** [comment]
I'm gonna call this done for now. Only issue is Forge updating. I'm not sure how to go about finding all the information to update that JSON. We can open another issue if we find any problems or you'd like to suggest additional functionality.

**Comment by Watchful1** [comment]
The only other idea I can think of is somehow notifying the user when the forge version changes, so they can update it themselves in MultiMC.

**Comment by Nincodedo** [comment]
I could log an error saying the Forge version of the pack is different than the currently installed one for this instance.

**Comment by Watchful1** [comment]
That would work.
