### ISSUE TITLE
Additional logging

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/ModPackDownloader#32]
Log an error saying the Forge version of the pack is different than the currently installed one for this instance when updating a modpack in MultiMC. Maybe also stop the pack from starting? @Watchful1

From #28

**Comment by Watchful1** [comment]
This is a bit tricky without multimc specific compatibility. Maybe write out a file with the current forge version when a pack is installed? So you can read it back again the next time the pack is updated. You probably know a lot more about it than me.

I don't know if it's possible to stop the pack from starting. From my initial look into the multimc code, it seems it starts minecraft regardless of what the pre-launch command does. You could do something to "break" the instance if the forge is wrong so it can't launch, but that seems a bit crude.

But at least logging the new forge version and a warning in big bold text at the top would be good.

**Comment by Nincodedo** [comment]
> This is a bit tricky without multimc specific compatibility. Maybe write out a file with the current forge version when a pack is installed? So you can read it back again the next time the pack is updated. You probably know a lot more about it than me.

Currently we back up the Curse manifest when updating the pack. We could backup the manifest by appending the version or file ID so we always have the previous versions. Reading the past Forge version from that would be pretty easy.

> I don't know if it's possible to stop the pack from starting. From my initial look into the multimc code, it seems it starts minecraft regardless of what the pre-launch command does. You could do something to "break" the instance if the forge is wrong so it can't launch, but that seems a bit crude.

I agree, wouldn't want to break the instance. I had thought I saw something that if the command returns with something other than 0, it would stop the pack from starting but I have a bad memory and could be wrong.

**Comment by Nincodedo** [comment]
Confirmed, we can stop the instance from running.

> Running Pre-Launch command: cmd.exe /c exit 1
> Process exited with code 1.
> Pre-Launch command failed with code 1.

So we can exit the app with something other than 0 if MultiMC Forge != manifest Forge.

**Comment by Watchful1** [comment]
Ah, sweet. That sounds perfect.
