### ISSUE TITLE
Curse download process changed?

### ISSUE THREAD

**Issue by Tsudico** [Nincraft/ModPackDownloader#39]
When trying to download a modpack today from Curse, the downloader only saved one ".jar" file, **minecraft.curseforge.com.jar**

It appears that Curse may have changed how the files are accessed on their system.

**Comment by Tsudico** [comment]
Contents of file shows the following:

Object moved to < a href="https://minecraft.curseforge.com/projects/226447-minecraft.curseforge.com/files/2307834/download">here</ a>

**Comment by Nincodedo** [comment]
This was fixed in 87771e1db1da297acc99749ec30d75182453392f and 262dc35570035d9085adca6cb45c502ed71962db. I can make a fix release some time this week.

**Comment by Nincodedo** [comment]
Or today https://github.com/Nincraft/ModPackDownloader/releases/tag/0.2.2

Let me know if you run into any other issues.

**Comment by Tsudico** [comment]
Looks like there might be multiple levels of redirects:

The .jar files I downloaded contained the following:

Object moved to <a href="https://addons-origin.cursecdn.com/files/2319/173/AbyssalCraft-1.10.2-1.9.2.7.jar">here</a>

That was for the AbyssalCraft jar, but each Jar has redirects instead of being a proper .jar file

**Comment by Nincodedo** [comment]
Did you clear out your cache? It might not actually be downloading the jars again and pulling what it already had from last time. Should be under C:\Users\USERNAME\.modpackdownloader if you're on Windows. If this doesn't fix this issue, could you post your manifest file? I'll have to debug through it.

**Comment by Tsudico** [comment]
I cleared out my cache and got the same result. Here is a copy of the manifest file.
[manifest.zip](https://github.com/Nincraft/ModPackDownloader/files/392680/manifest.zip)

**Comment by Nincodedo** [comment]
Yup, missed a redirect. https://github.com/Nincraft/ModPackDownloader/releases/tag/0.2.3 Thanks for the catch! This should fix things.

**Comment by Tsudico** [comment]
That seems to have fixed it. Thank you!
