### ISSUE TITLE
Separate Processing Logic

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/ModPackDownloader#40]
So basically instead of one mod list manager handling downloads and updates to a single manifest, I'm thinking we can have processors for each, well, process.  Updating can take in a list of manifest file locations, build out the manifests given the files at those locations, and update them.  Downloading can take in its own list of manifest file locations, compile them to a singular list of mods to download, and download them to the output location provided in the arguments.  Modpack Updating will eventually just be split out into its own processor (I personally am not planning on changing its logic, just where it happens with this feature).  The new feature that will come with this is merging manifest files, which will take in a list of manifest file locations, convert them all into their own manifests, pull out all distinct curse mods found within them into a single mod list, then dump that back into a new manifest, which will be written to the output folder given in the arguments.  This will allow us to pull in all of our individual manifests into one cohesive Curse Manifest for automatically deploying modpacks to CurseForge.

**Comment by Nincodedo** [comment]
This is basically done. The modpack downloading is not separated out to this logic, however it may be removed in a future version so I don't want to invest too much time into it.
