### ISSUE TITLE
Curse manifest: minecraft.curseforge.com?

### ISSUE THREAD

**Issue by rosaParvum** [Nincraft/ModPackDownloader#42]
When I run the program, it looks like it works, but produces a jar file named minecraft.curseforge.com.
What's going on?  
![image](https://cloud.githubusercontent.com/assets/9846598/19835381/c11f1ee4-9e7c-11e6-9641-c88d93974689.png)

**Comment by Nincodedo** [comment]
Can you post the logs, what version you're using and the manifest you used?

**Comment by Nincodedo** [comment]
No response for 2 days. Reopen this issue and post the logs, ModPack Downloader version, and Curse manifest if you're still having issues.
