### ISSUE TITLE
All downloads fail - possible Curse URL change?

### ISSUE THREAD

**Issue by N-kay** [Nincraft/ModPackDownloader#53]
[Log on pastebin](http://pastebin.com/EJa8snzh)

Valid URL would be
`https://minecraft.curseforge.com/projects/storage-drawers/files/2350060/download?cookieTest=1`
but Downloader tries to get
`https://minecraft.curseforge.com/projects/223852-storage-drawers/files/2350060/download?cookieTest=1`

Notice the missing project-id in the URL. I'm guessing this must be a recent change on their side.
I tried the manifest from [In The Sea](https://minecraft.curseforge.com/projects/in-the-sea) and [SkyExchange](https://minecraft.curseforge.com/projects/skyexchange).

**Comment by Nincodedo** [comment]
Thanks, working on a fix now.

**Comment by Nincodedo** [comment]
Fixed. https://github.com/Nincraft/ModPackDownloader/releases/tag/0.3.1

Please let me know if this is still an issue.
