### ISSUE TITLE
Some multi-threads fail to connect.

### ISSUE THREAD

**Issue by Bucket777** [Nincraft/ModPackDownloader#54]
Having trouble downloading packs fully (Trying with Skyfactory3).

My internet connection isn't always wonderfull, but as you will notice from the logs the most of multiple threads timeout or loses connection to curse/nincraft. The result is that only 4-10 mods is being verified each run and I have to run the app many times.

Also, when running with the [-updateCurseModPack] parameter it fails to download the latest .zip file.
If I manually download and place it in the folder it works.

[manifest.zip](https://github.com/Nincraft/ModPackDownloader/files/691277/manifest.zip)
[modPackDownloader.zip](https://github.com/Nincraft/ModPackDownloader/files/691278/modPackDownloader.zip)

**Comment by Nincodedo** [comment]
0.3.2 adds a maxDownloadThreads parameter. If you set this to a low number it should help with your internet issues.

https://github.com/Nincraft/ModPackDownloader/releases/tag/0.3.2

Still need to look into the updateCurseModPack issue.
