### ISSUE TITLE
Github Downloads result in 0KB jar Files

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/ModPackDownloader#6]
For some reason two mods that I have set up to download from GitHub in TWBB are resulting in 0KB jar files when using the downloader, but going and manually downloading them is fine.

For more information, see: https://github.com/UndeadZeratul/ThereWillBeBlood/issues/110

**Comment by Nincodedo** [comment]
Can confirm this happens, dunno why. More investigating is needed.

**Comment by Nincodedo** [comment]
https > http

**Comment by UndeadZeratul** [comment]
ya srsly... Both download URLs return the same mimetype, the same URL redirects, the only difference between the working botania URL and the non-working Better Storage ones is the `https`
