### ISSUE TITLE
Newb using 0.41

### ISSUE THREAD

**Issue by Bucket777** [Nincraft/ModPackDownloader#60]
Might by me not understanding the output of the logs...
 
But the new version is giving me errors.

[CMDError.txt](https://github.com/Nincraft/ModPackDownloader/files/922564/CMDError.txt)
[modPackDownloader.txt](https://github.com/Nincraft/ModPackDownloader/files/922561/modPackDownloader.txt)

any help please?

**Comment by Nincodedo** [comment]
I broke something. Should be fixed now.

https://github.com/Nincraft/ModPackDownloader/releases/tag/0.4.2

Let me know if you're still having issues.

**Comment by Bucket777** [comment]
It seems to be downloading better, but still seeing the errors on Win10 CMD and it does not exit after downloading all the mods - have to ctrl+c to stop it.

[modPackDownloader0.42.txt](https://github.com/Nincraft/ModPackDownloader/files/922728/modPackDownloader0.42.txt)
![capture](https://cloud.githubusercontent.com/assets/13619986/25052548/a8f9838c-2152-11e7-86ed-44ba53becbc8.PNG)

**Comment by Nincodedo** [comment]
Does it always not exit? I'm not able to recreate that issue.

I am aware of the console output being messed up, still gotta fix that.

**Comment by Bucket777** [comment]
Okay its working every time now.

Thanks

**Comment by Nincodedo** [comment]
Console logging fixed in 0.4.3

https://github.com/Nincraft/ModPackDownloader/releases/tag/0.4.3
