### ISSUE TITLE
Java 8u131 Crash?

### ISSUE THREAD

**Issue by Bucket777** [Nincraft/ModPackDownloader#67]
I get a java stopped working error when trying to update my mod pack with the 0.4.3 version.

[JavaCrash.txt](https://github.com/Nincraft/ModPackDownloader/files/1105273/JavaCrash.txt)
[modPackDownloader.txt](https://github.com/Nincraft/ModPackDownloader/files/1105272/modPackDownloader.txt)

not sure if it is java or not, but the javaw can still launch minecraft...

**Comment by Nincodedo** [comment]
Huh..... I'll have to try and debug this. I'm not sure why this is happening.

**Comment by Nincodedo** [comment]
What are your OS and Java details? Are you running 64 bit Java on 64 bit Windows?

**Comment by Nincodedo** [comment]
Cannot recreate. I did not get this error when running Java 8u131.

**Comment by Bucket777** [comment]
Thanks for the quick response. It is working today, must have been a bad internet connection.

**Comment by Nincodedo** [comment]
Huh, weird. Glad it's working again!
