### ISSUE TITLE
All downloads getting either connection reset or time out

### ISSUE THREAD

**Issue by joosera** [Nincraft/ModPackDownloader#68]
I have used ModPackDownloader previously fine but now when trying to update a new version of a modpack all the downloads just get a connection reset or a timeout.
Most of my downloaded files already exist in my local cache so they are fine, but any updated mods don't get downloaded.

Example in my logs (See whole log at [modPackDownloader.txt](https://github.com/Nincraft/ModPackDownloader/files/1167584/modPackDownloader.txt)):
1. Connection reset
```
...
22:16:09.359 [pool-2-thread-23] INFO  com.nincraft.modpackdownloader.util.DownloadHelper:77 - Successfully moved from cache Botania r1.8-249.jar
22:16:09.503 [pool-2-thread-82] ERROR com.nincraft.modpackdownloader.handler.CurseFileHandler:44 - java.net.SocketException: Connection reset
22:16:09.639 [pool-2-thread-101] INFO  com.nincraft.modpackdownloader.util.DownloadHelper:77 - Successfully moved from cache MrCrayfishFurnitureModv3.4.7(1.7.10).jar
...
```

2. Timeout
```
...
22:16:25.453 [pool-2-thread-115] INFO  com.nincraft.modpackdownloader.util.DownloadHelper:77 - Successfully moved from cache p455w0rdslib-1.7.10-1.0.4.jar
22:16:26.671 [pool-2-thread-149] ERROR com.nincraft.modpackdownloader.handler.CurseFileHandler:44 - java.net.ConnectException: Connection timed out: connect
22:16:27.165 [pool-2-thread-134] INFO  com.nincraft.modpackdownloader.util.DownloadHelper:77 - Successfully moved from cache Reliquary-1.7.10-1.2.1.483.jar
...
```

Looking up the fileids up from the manifest files I can guess what files are missing and download them manually through my web browser and just place them in my mods folder, but that feels a bit counter productive 😄

**Comment by Nincodedo** [comment]
I would suggest using the -maxDownloadThreads argument and setting it to something like 10 or 15. Without that MPD will just try to download all the mods at the same time which can be an issue with larger packs. Let me know if that helps and if not we can rework some other stuff.

**Comment by joosera** [comment]
Oh yeah, that would make sense. So I guess I was interpreting the log file wrong and actually it was just random downloads that timed out.

I guess this argument should be mentioned in the documentation 😄 

But yeah, this fixes my problem.

**Comment by Nincodedo** [comment]
Glad to hear it's fixed! And yeah, the documentation needs an update for sure.
