### ISSUE TITLE
Downloading an Alpha Release from Curse in Thirdparty Mods Fails Unless Using Direct Link

### ISSUE THREAD

**Issue by UndeadZeratul** [Nincraft/ModPackDownloader#7]
So far only applies to Tinkers' Construct v1.8.8-build991, but it just doesn't want to download the mod at all unless I use the CurseForge CDN URL instead of the "official" download link from the button itself.

For more information, see: https://github.com/UndeadZeratul/ThereWillBeBlood/issues/110

**Comment by Nincodedo** [comment]
This fails since we're using the curse link and not curse forge. Alphas are not synced to curse. We'll need to either switch to using curse forge links or add a special case for alphas.

**Comment by UndeadZeratul** [comment]
I'd say use CurseForge all the time to stay consistent.

**Comment by Nincodedo** [comment]
Apparently we're already using a Curse Forge link :| https://github.com/Nincraft/ModPackDownloader/blob/6995bdd0c9a52c259399e1cb38ccfe7924a8326a/src/main/java/com/nincraft/modpackdownloader/util/Reference.java#L4

**Comment by Nincodedo** [comment]
I was able to download Extra Utilities 2 alpha as a Curse mod with the current build. I'm not sure why we were getting this issue before but we should retest.

**Comment by UndeadZeratul** [comment]
The related issue in TWBB has been fixed; TiC worked as a curse mod (idk how it broke before, whatever) and changing protocol to `https` fixed the two github mods.  We can look into handling these correctly later, but for now this issue can be closed.
