### ISSUE TITLE
downloader does not find modpack on curse/ftb

### ISSUE THREAD

**Issue by Bucket777** [Nincraft/ModPackDownloader#70]
Hi,

not sure if this is working as intended, but I cannot download a modpack without getting the zip from curse and extracting the manifest (even with -updateCurseModpack in the command).

Also, when will the gui how to be available, can't be sure if I'm doing something wrong...but nothing downloads from it.

[modPackDownloader.txt](https://github.com/Nincraft/ModPackDownloader/files/1306074/modPackDownloader.txt)

Thanks

**Comment by Nincodedo** [comment]
What version of the downloader are you using?

**Comment by Bucket777** [comment]
ModpackDownloader-cli-0.5.312
