### ISSUE TITLE
External 503 causing test failures

### ISSUE THREAD

**Issue by NathanZook** [Nincraft/ModPackDownloader#72]
Running Mint Linux.
Compile passes.  CLI tests failing attempting to update Thaumcraft.  The external server is returning a 503.  This is causing a test fail which prevents the build.

**Comment by Nincodedo** [comment]
Thank you, I'll look into this tonight.

**Comment by Nincodedo** [comment]
Looks like the Curse Widget API we use for updating is unavailable due to changes on Curse. For the time being, we'll skip this test and disable updating until the Widget API has been fixed or we find an alternative method of updating.

**Comment by NathanZook** [comment]
When I disabled the test, the code ran (I was pulling down SF 2.5.6), although there were 5 mods that were unavailable.  I'm  a huge TDDer myself, but I'm not so sure about disabling functionality that generally works.  Your call, of course.

**Comment by Nincodedo** [comment]
The mod updating process completely relies on the Curse Widget API so without that it's broken. That's why I disabled it. Downloading works fine without it.
