### ISSUE TITLE
Error: Error: Invalid or corrupt jarfile ModpackDownloader-gui-0.5.2.325.jar

### ISSUE THREAD

**Issue by Nawor3565** [Nincraft/ModPackDownloader#76]
When trying to run the GUI, either through double-clicking the .jar or with CMD, I get this message:
`Error: Invalid or corrupt jarfile ModpackDownloader-gui-0.5.2.325.jar`
After that, nothing happens. No log file made.

**Comment by Nawor3565** [comment]
Hold on, it looks like the GUI jar file for the latest version is only 288KB, while in past versions it's been over 6MB. The CLI jar is fine. Did something happen when compiling the 0.5.2.325 GUI jar?

GUI version 0.5.2.319 launches fine, but downloading from Curse doesn't work, since that's what the latest update fixed.

**Comment by Nincodedo** [comment]
Reuploaded GUI jar. Should be good now
